name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 10.15

      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: ./back

      - name: Build backend with Yarn
        run: yarn run build:prod
        working-directory: ./back

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: nsa_back
          path: |
            back
            !back/**/*.md