name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'

      - name: Update Composer
        run: composer update
        working-directory: ./back

      - name: Install dependencies
        run: composer install
        working-directory: ./back

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        working-directory: ./back

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: nsa_back
          path: |
            back
            !back/**/*.md