name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 10.15
          #cache: 'yarn'

      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: ./front

      - name: Build frontend with Yarn
        run: yarn run build:prod
        working-directory: ./front

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: nsa_front
          path: |
            front
            !front/**/*.md

      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ansible-playbook -i inventory.ini deploy.yml
